### ISSUE TITLE
kkok.sendAlerts ignores Alert.Routes

### ISSUE THREAD

**Issue by uchan-nos** [cybozu-go/kkok#2]
I found a bug with the route selection.
An alert will be delivered to all routes configured in a toml file
even if its `routes` attribute has a subset of routes.

I'm writing a patch to fix the problem.
It fixes mainly [`sendAlerts`](https://github.com/cybozu-go/kkok/blob/cc3ed3d867a8433650c966f54bc3d320b9411794/kkok.go#L217) function as follows:

- use `Alert.Routes` attribute
- send an alert to a route only if `Routes` of the alert contains the route.

**Comment by uchan-nos** [comment]
I have written a patch https://github.com/cybozu-go/kkok/pull/4.
Could anyone review this PR? :-)

**Comment by ymmt2005** [comment]
I will.
